language: php
php:
  - '7.4'
  - '8.0'
  - nightly
before_script: composer update
script: 
    - vendor/bin/phpunit --configuration phpunit.dist.xml
after_success:
    - curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --import
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
    - curl -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
    - gpg --verify codecov.SHA256SUM.sig codecov.SHA256SUM
    - shasum -a 256 -c codecov.SHA256SUM
    - chmod +x codecov
    - ./codecov -f ./coverage.xml