language: php
php:
  - '8.1'
  - '8.2'
  - '8.3'
  - '8.4'
  - nightly
before_script: composer update
script: 
    - vendor/bin/phpunit --configuration phpunit.dist.xml
after_success:
    - bash <(curl -s https://codecov.io/bash)