language: php
php:
  - '7.4'
  - '8.0'
  - nightly
before_script: composer update
script: 
    - vendor/bin/phpunit --configuration phpunit.dist.xml --coverage-clover coverage.xml
after_success:
    - bash <(curl -s https://codecov.io/bash)